# Generated by Django 2.2.9 on 2023-01-20 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221229_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
