# Generated by Django 2.2.16 on 2023-02-11 12:06

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(db_index=True, help_text='Текст нового поста', validators=[posts.validators.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
