# Generated by Django 2.2.16 on 2023-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20230228_1838'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='only_one_sub'),
        ),
    ]
